services:
  grafana:
    image: grafana/grafana:11.1.2
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=CHANGEME
    volumes:
      - ./config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/config.yaml
      - ./config/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/config.yaml
      - ./config/grafana-dashboard.json:/var/lib/grafana/dashboards/rq.json
    ports:
      - 3000:3000
    networks:
      - poc

  prometheus:
    image: prom/prometheus:v2.53.2
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - poc

  elasticsearch:
    image: elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=CHANGEME
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -X GET -k -u elastic:CHANGEME https://localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 15s
    networks:
      - poc

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.59
    container_name: jaeger-collector
    environment:
      - ADMIN_HTTP_HOST_PORT=:14269
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_USERNAME=elastic
      - ES_PASSWORD=CHANGEME
      - ES_SERVER_URLS=https://elasticsearch:9200
      - ES_TLS_ENABLED=true
      - ES_TLS_SKIP_HOST_VERIFY=true
      - COLLECTOR_OTLP_GRPC_HOST_PORT=0.0.0.0:4317
      - COLLECTOR_OTLP_HTTP_HOST_PORT=0.0.0.0:4318
    ports:
      - 14269:14269
    expose:
      - 4317
      - 4318
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - poc

  jaeger-query:
    image: jaegertracing/jaeger-query:1.59
    container_name: jaeger-query
    environment:
      - ADMIN_HTTP_HOST_PORT=:16687
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_USERNAME=elastic
      - ES_PASSWORD=CHANGEME
      - ES_SERVER_URLS=https://elasticsearch:9200
      - ES_TLS_ENABLED=true
      - ES_TLS_SKIP_HOST_VERIFY=true
    ports:
      - 16686:16686
      - 16687:16687
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - poc

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.106.1
    container_name: otel-collector
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./config/otel-collector.yaml:/etc/otel/config.yaml
    command: ["--config", "/etc/otel/config.yaml"]
    networks:
      - poc

  redis:
    image: redis:alpine3.20
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - poc

networks:
  poc:
